# Generated by Django 4.1.7 on 2023-09-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraceTypicalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('height', models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='высота, м')),
                ('width', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='ширина, м')),
                ('length', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='длина, м')),
                ('frame_material', models.CharField(max_length=250, verbose_name='материал каркаса')),
                ('frame_width', models.PositiveSmallIntegerField(null=True, verbose_name='ширина каркаса, мм')),
                ('frame_thickness', models.PositiveSmallIntegerField(null=True, verbose_name='толщина каркаса, мм')),
                ('coloring', models.CharField(max_length=250, verbose_name='окраска')),
                ('flooring_material', models.CharField(max_length=250, verbose_name='материал настила')),
                ('extra', models.CharField(blank=True, max_length=250, verbose_name='дополнительно')),
            ],
            options={
                'verbose_name': 'типовой проект',
                'verbose_name_plural': 'типовой проект',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Terrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=80, verbose_name='title')),
                ('meta_description', models.CharField(max_length=160, verbose_name='meta description')),
                ('name', models.CharField(max_length=80, verbose_name='h1-название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='url-адрес страницы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('description_title', models.CharField(blank=True, max_length=200, verbose_name='заголовок')),
                ('description_text', models.TextField(blank=True, verbose_name='текст')),
                ('portfolio_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('block_railings', models.ManyToManyField(blank=True, db_index=True, related_name='+', to='blocks.blockimage', verbose_name='объекты')),
                ('hwaw', models.ManyToManyField(blank=True, db_index=True, related_name='+', to='blocks.blocksvg', verbose_name='объекты')),
                ('typical_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='terraces.terracetypicalproject', verbose_name='типовой проект')),
            ],
            options={
                'verbose_name': 'терраса',
                'verbose_name_plural': 'террасы',
            },
        ),
    ]
