# Generated by Django 4.1.7 on 2023-06-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0002_terrace_block_railings_terrace_block_railings_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraceTypicalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveSmallIntegerField(verbose_name='длина')),
                ('width', models.PositiveSmallIntegerField(verbose_name='ширина')),
                ('height', models.PositiveSmallIntegerField(verbose_name='высота')),
                ('coloring', models.CharField(max_length=250, verbose_name='Окраска')),
                ('frame', models.CharField(max_length=250, verbose_name='Каркас')),
                ('railing', models.CharField(max_length=250, verbose_name='Ограждение')),
                ('handrail', models.CharField(max_length=250, verbose_name='Поручень')),
                ('flooring', models.CharField(max_length=250, verbose_name='Настил')),
            ],
            options={
                'verbose_name': 'типовой проект террасы',
                'verbose_name_plural': 'типовой проект террасы',
            },
        ),
    ]
