# Generated by Django 4.1.7 on 2023-06-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_alter_blocksvg_block_name'),
        ('terraces', '0002_remove_terrace_block_railings_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrace',
            name='block_railings',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='+', to='blocks.blockimage', verbose_name='ограждения'),
        ),
    ]
