# Generated by Django 4.1.7 on 2023-06-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0003_terracetypicalproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terracetypicalproject',
            options={'verbose_name': 'типовой проект', 'verbose_name_plural': 'типовой проект'},
        ),
    ]
