# Generated by Django 4.1.7 on 2023-06-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0004_alter_terracetypicalproject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='coloring',
            field=models.CharField(max_length=250, verbose_name='окраска'),
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='flooring',
            field=models.CharField(max_length=250, verbose_name='настил'),
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='frame',
            field=models.CharField(max_length=250, verbose_name='каркас'),
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='handrail',
            field=models.CharField(max_length=250, verbose_name='поручень'),
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='высота'),
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='length',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='длина'),
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='railing',
            field=models.CharField(max_length=250, verbose_name='ограждение'),
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='ширина'),
        ),
    ]
