# Generated by Django 4.1.7 on 2023-06-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0005_alter_terracetypicalproject_coloring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terracetypicalproject',
            name='handrail',
        ),
        migrations.RemoveField(
            model_name='terracetypicalproject',
            name='railing',
        ),
        migrations.AddField(
            model_name='terracetypicalproject',
            name='color',
            field=models.CharField(default='', max_length=250, verbose_name='цвет'),
            preserve_default=False,
        ),
    ]
