# Generated by Django 4.1.7 on 2023-06-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0006_remove_terracetypicalproject_handrail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terracetypicalproject',
            name='color',
        ),
    ]
