# Generated by Django 4.1.7 on 2023-06-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0008_terracetypicalproject_frame_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terracetypicalproject',
            name='frame_length',
        ),
    ]
