# Generated by Django 4.1.7 on 2023-06-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0009_remove_terracetypicalproject_frame_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terracetypicalproject',
            old_name='flooring',
            new_name='flooring_material',
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='frame_thickness',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='толщина, мм'),
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='frame_width',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='ширина, мм'),
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='высота, м'),
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='length',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='длина, м'),
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='ширина, м'),
        ),
    ]
