# Generated by Django 4.1.7 on 2023-06-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0011_alter_terracetypicalproject_flooring_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='высота, м'),
        ),
    ]
