# Generated by Django 4.1.7 on 2023-06-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0012_alter_terracetypicalproject_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='высота, м'),
        ),
    ]
