# Generated by Django 4.1.7 on 2023-06-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0013_alter_terracetypicalproject_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terracetypicalproject',
            old_name='frame',
            new_name='frame_material',
        ),
    ]
