# Generated by Django 4.1.7 on 2023-06-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0014_rename_frame_terracetypicalproject_frame_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='frame_material',
            field=models.CharField(max_length=250, verbose_name='материал каркаса'),
        ),
    ]
