# Generated by Django 4.1.7 on 2023-06-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0015_alter_terracetypicalproject_frame_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='frame_thickness',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='толщина каркаса, мм'),
        ),
        migrations.AlterField(
            model_name='terracetypicalproject',
            name='frame_width',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='ширина каркаса, мм'),
        ),
    ]
