# Generated by Django 4.1.7 on 2023-06-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0016_alter_terracetypicalproject_frame_thickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrace',
            name='typical_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='terraces.terracetypicalproject', verbose_name='типичный проект'),
        ),
    ]
