# Generated by Django 4.1.7 on 2023-06-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0017_terrace_typical_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='terracetypicalproject',
            name='name',
            field=models.CharField(default='Типовой проект террасы', max_length=250, verbose_name='название'),
            preserve_default=False,
        ),
    ]
