# Generated by Django 4.1.7 on 2023-06-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraces', '0018_terracetypicalproject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='terracetypicalproject',
            name='extra',
            field=models.CharField(blank=True, max_length=250, verbose_name='дополнительно'),
        ),
    ]
