# Generated by Django 4.1.7 on 2023-06-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=1, verbose_name='показывать'),
        ),
    ]
