# Generated by Django 4.1.7 on 2023-05-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_name_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='аттрибут title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=255, unique=True, verbose_name='ссылка'),
        ),
    ]
