# Generated by Django 4.1.7 on 2023-06-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPage',
            new_name='Contacts',
        ),
    ]
