# Generated by Django 4.1.7 on 2023-09-21 08:02

import blocks.models
import common.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('img_path', models.FileField(blank=True, null=True, upload_to=common.helpers.get_image_path, verbose_name='путь к картинке')),
                ('price', models.PositiveIntegerField(verbose_name='цена, руб.')),
            ],
            options={
                'verbose_name': 'Блок с ценой',
                'verbose_name_plural': 'Блоки с ценами',
            },
        ),
        migrations.CreateModel(
            name='BlockText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'текстовый блок',
                'verbose_name_plural': 'текстовые блоки',
            },
        ),
        migrations.CreateModel(
            name='BlockSVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('block_name', models.CharField(max_length=80, verbose_name='название блока')),
                ('description', models.TextField(verbose_name='описание')),
                ('order_number', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
                ('svg_path', models.FileField(default='empty.svg', upload_to=common.helpers.get_svg_path, validators=[blocks.models.validate_svg_path], verbose_name='путь к svg файлу')),
            ],
            options={
                'verbose_name': 'блок с векторной графикой',
                'verbose_name_plural': 'блоки с векторной графикой',
                'ordering': ['order_number'],
                'unique_together': {('block_name', 'title')},
            },
        ),
        migrations.CreateModel(
            name='BlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('img_path', models.FileField(blank=True, null=True, upload_to=common.helpers.get_image_path, verbose_name='путь к картинке')),
                ('block_name', models.CharField(max_length=80, verbose_name='название блока')),
                ('is_zoom', models.BooleanField(db_index=True, default=1, verbose_name='увеличивать')),
                ('order_number', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
            ],
            options={
                'verbose_name': 'Блок с картинкой',
                'verbose_name_plural': 'Блоки с картинками',
                'ordering': ['order_number'],
                'unique_together': {('block_name', 'title')},
            },
        ),
    ]
