# Generated by Django 4.1.7 on 2023-06-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockimage',
            name='block_name',
            field=models.CharField(max_length=80, verbose_name='название блока'),
        ),
    ]
