# Generated by Django 4.1.7 on 2023-06-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_alter_blockimage_is_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockimage',
            name='is_zoom',
            field=models.BooleanField(db_index=True, default=1, verbose_name='увеличивать'),
        ),
    ]
