# Generated by Django 4.1.7 on 2023-06-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_alter_blockimage_is_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockimage',
            name='block_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='название блока'),
        ),
        migrations.AlterUniqueTogether(
            name='blockimage',
            unique_together={('block_name', 'title')},
        ),
    ]
