# Generated by Django 4.1.7 on 2023-06-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_blockimage_block_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktext',
            name='title',
            field=models.CharField(default=0, max_length=200, verbose_name='заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockimage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='blockprice',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
    ]
