# Generated by Django 4.1.7 on 2023-06-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_blocktext_title_alter_blockimage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockimage',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер'),
        ),
    ]
