# Generated by Django 4.1.7 on 2023-06-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_blockimage_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockimage',
            options={'ordering': ['order_number'], 'verbose_name': 'Блок с картинкой', 'verbose_name_plural': 'Блоки с картинками'},
        ),
    ]
