# Generated by Django 4.1.7 on 2023-06-29 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorchTypicalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('height', models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='высота, м')),
                ('width', models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='ширина, м')),
                ('depth', models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='глубина, м')),
                ('frame_kosour_count', models.PositiveSmallIntegerField(null=True, verbose_name='количество косоуров')),
                ('frame_material', models.CharField(max_length=250, verbose_name='материал каркаса')),
                ('frame_width', models.PositiveSmallIntegerField(null=True, verbose_name='ширина каркаса, мм')),
                ('frame_thickness', models.PositiveSmallIntegerField(null=True, verbose_name='толщина каркаса, мм')),
                ('coloring', models.CharField(max_length=250, verbose_name='окраска')),
                ('steps_material', models.CharField(max_length=250, verbose_name='материал ступеней')),
                ('steps_height', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='высота ступеней, м')),
                ('extra', models.CharField(blank=True, max_length=250, verbose_name='дополнительно')),
            ],
            options={
                'verbose_name': 'типовой проект',
                'verbose_name_plural': 'типовой проект',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Porch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=80, verbose_name='title')),
                ('meta_description', models.CharField(max_length=160, verbose_name='meta description')),
                ('name', models.CharField(max_length=80, verbose_name='h1-название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='url-адрес страницы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('description_title', models.CharField(blank=True, max_length=200, verbose_name='заголовок')),
                ('description_text', models.TextField(blank=True, verbose_name='текст')),
                ('menu_name', models.CharField(max_length=80, verbose_name='название для меню')),
                ('menu_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер в меню')),
                ('block_railings', models.ManyToManyField(blank=True, db_index=True, related_name='+', to='blocks.blockimage', verbose_name='объекты')),
                ('hwaw', models.ManyToManyField(blank=True, db_index=True, related_name='+', to='blocks.blocksvg', verbose_name='объекты')),
                ('typical_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='porch.porchtypicalproject', verbose_name='типовой проект')),
            ],
            options={
                'verbose_name': 'крыльцо',
                'verbose_name_plural': 'крыльцо',
                'ordering': ('menu_order',),
            },
        ),
    ]
