# Generated by Django 4.1.7 on 2023-09-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porch',
            options={'verbose_name': 'крыльцо', 'verbose_name_plural': 'крыльцо'},
        ),
        migrations.RemoveField(
            model_name='porch',
            name='menu_name',
        ),
        migrations.RemoveField(
            model_name='porch',
            name='menu_order',
        ),
    ]
