# Generated by Django 4.1.7 on 2023-06-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_alter_blockimage_options'),
        ('porch', '0002_remove_porch_portfolio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='porch',
            name='block_railings',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='+', to='blocks.blockimage', verbose_name='"Контент"'),
        ),
        migrations.AddField(
            model_name='porch',
            name='block_railings_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
    ]
