# Generated by Django 4.1.7 on 2023-06-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0002_porch_hwaw'),
    ]

    operations = [
        migrations.AddField(
            model_name='porch',
            name='portfolio_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
    ]
