# Generated by Django 4.1.7 on 2023-06-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0003_porch_block_railings_porch_block_railings_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorchTypicalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='длина, м')),
                ('width', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ширина, м')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='высота, м')),
                ('frame_material', models.CharField(max_length=250, verbose_name='материал каркаса')),
                ('frame_kosour_count', models.PositiveSmallIntegerField(verbose_name='количество косоуров, мм')),
                ('frame_width', models.PositiveSmallIntegerField(verbose_name='ширина каркаса, мм')),
                ('frame_thickness', models.PositiveSmallIntegerField(verbose_name='толщина каркаса, мм')),
                ('coloring', models.CharField(max_length=250, verbose_name='окраска')),
                ('steps_material', models.CharField(max_length=250, verbose_name='материал ступеней')),
                ('steps_height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='высота ступеней, м')),
                ('steps_length', models.PositiveSmallIntegerField(verbose_name='длина ступеней, мм')),
                ('steps_width', models.PositiveSmallIntegerField(verbose_name='ширина ступеней, мм')),
                ('steps_thickness', models.PositiveSmallIntegerField(verbose_name='толщина ступеней, мм')),
            ],
            options={
                'verbose_name': 'типовой проект',
                'verbose_name_plural': 'типовой проект',
            },
        ),
    ]
