# Generated by Django 4.1.7 on 2023-06-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0004_porchtypicalproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='длина, м'),
        ),
    ]
