# Generated by Django 4.1.7 on 2023-06-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0005_alter_porchtypicalproject_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='высота, м'),
        ),
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='steps_height',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='высота ступеней, м'),
        ),
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='ширина, м'),
        ),
    ]
