# Generated by Django 4.1.7 on 2023-06-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0006_alter_porchtypicalproject_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='frame_kosour_count',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='количество косоуров, мм'),
        ),
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='frame_thickness',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='толщина каркаса, мм'),
        ),
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='frame_width',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='ширина каркаса, мм'),
        ),
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='steps_length',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='длина ступеней, мм'),
        ),
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='steps_thickness',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='толщина ступеней, мм'),
        ),
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='steps_width',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='ширина ступеней, мм'),
        ),
    ]
