# Generated by Django 4.1.7 on 2023-06-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0007_alter_porchtypicalproject_frame_kosour_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porchtypicalproject',
            name='steps_length',
        ),
        migrations.RemoveField(
            model_name='porchtypicalproject',
            name='steps_width',
        ),
    ]
