# Generated by Django 4.1.7 on 2023-06-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0008_remove_porchtypicalproject_steps_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='frame_kosour_count',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='количество косоуров'),
        ),
    ]
