# Generated by Django 4.1.7 on 2023-06-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0009_alter_porchtypicalproject_frame_kosour_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='высота, м'),
        ),
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='length',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='длина, м'),
        ),
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='ширина, м'),
        ),
    ]
