# Generated by Django 4.1.7 on 2023-06-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0010_alter_porchtypicalproject_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='length',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='длина, м'),
        ),
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='ширина, м'),
        ),
    ]
