# Generated by Django 4.1.7 on 2023-06-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0011_alter_porchtypicalproject_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porchtypicalproject',
            name='steps_thickness',
        ),
    ]
