# Generated by Django 4.1.7 on 2023-06-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0012_remove_porchtypicalproject_steps_thickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='porchtypicalproject',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='название'),
            preserve_default=False,
        ),
    ]
