# Generated by Django 4.1.7 on 2023-06-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0013_porchtypicalproject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='porch',
            name='typical_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='porch.porchtypicalproject', verbose_name='типичный проект'),
        ),
    ]
