# Generated by Django 4.1.7 on 2023-06-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0014_porch_typical_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porchtypicalproject',
            name='length',
        ),
        migrations.AddField(
            model_name='porchtypicalproject',
            name='depth',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='глубина, м'),
        ),
    ]
