# Generated by Django 4.1.7 on 2023-06-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0015_remove_porchtypicalproject_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porchtypicalproject',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='высота, м'),
        ),
    ]
