# Generated by Django 4.1.7 on 2023-06-21 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porch', '0017_porchtypicalproject_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porch',
            name='typical_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='porch.porchtypicalproject', verbose_name='типовой проект'),
        ),
    ]
