# Generated by Django 4.1.7 on 2023-05-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Railing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=80, verbose_name='title')),
                ('meta_description', models.CharField(max_length=160, verbose_name='meta description')),
                ('meta_keywords', models.CharField(max_length=160, verbose_name='meta keywords')),
                ('name', models.CharField(max_length=80, verbose_name='название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='url-адрес страницы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('description_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('description_text', models.TextField(blank=True, verbose_name='Текст')),
                ('menu_name', models.CharField(blank=True, max_length=80, verbose_name='название для меню')),
                ('menu_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер в меню')),
            ],
            options={
                'verbose_name': 'перила',
                'verbose_name_plural': 'перила',
                'ordering': ('menu_order',),
            },
        ),
    ]
