# Generated by Django 4.1.7 on 2023-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='railing',
            name='portfolio_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
    ]
