# Generated by Django 4.1.7 on 2023-09-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaircaseTypicalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('frame_broken_material', models.CharField(blank=True, max_length=250, verbose_name='материал "ломаного" каркаса')),
                ('frame_broken_width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ширина "ломаного" каркаса, мм')),
                ('frame_broken_thickness', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='толщина "ломаного" каркаса, мм')),
                ('frame_straight_material', models.CharField(blank=True, max_length=250, verbose_name='материал "прямого" каркаса')),
                ('frame_straight_width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ширина "прямого" каркаса, мм')),
                ('frame_straight_thickness', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='толщина "прямого" каркаса, мм')),
                ('coloring', models.CharField(max_length=250, verbose_name='окраска')),
                ('steps_material', models.CharField(max_length=250, verbose_name='материал ступеней')),
                ('steps_height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='высота ступеней, м')),
            ],
            options={
                'verbose_name': 'типовой проект',
                'verbose_name_plural': 'типовой проект',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staircase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=80, verbose_name='title')),
                ('meta_description', models.CharField(max_length=160, verbose_name='meta description')),
                ('name', models.CharField(max_length=80, verbose_name='h1-название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='url-адрес страницы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('description_title', models.CharField(blank=True, max_length=200, verbose_name='заголовок')),
                ('description_text', models.TextField(blank=True, verbose_name='текст')),
                ('menu_name', models.CharField(max_length=80, verbose_name='название для меню')),
                ('menu_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер в меню')),
                ('portfolio_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('block_price_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('block_svg_title', models.CharField(blank=True, max_length=200, verbose_name='заголовок')),
                ('is_calculator', models.BooleanField(default=1, verbose_name='показывать')),
                ('block_price', models.ManyToManyField(blank=True, db_index=True, related_name='+', to='blocks.blockprice', verbose_name='объекты')),
                ('block_railings', models.ManyToManyField(blank=True, db_index=True, related_name='+', to='blocks.blockimage', verbose_name='объекты')),
                ('block_svg', models.ManyToManyField(blank=True, db_index=True, related_name='block_svg', to='blocks.blocksvg', verbose_name='объекты')),
                ('hwaw', models.ManyToManyField(blank=True, db_index=True, related_name='+', to='blocks.blocksvg', verbose_name='объекты')),
                ('typical_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staircases.staircasetypicalproject', verbose_name='типовой проект')),
            ],
            options={
                'verbose_name': 'лестницу',
                'verbose_name_plural': 'лестницы',
                'ordering': ('menu_order',),
            },
        ),
    ]
