# Generated by Django 4.1.7 on 2023-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        ('staircases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staircase',
            name='hwaw',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='+', to='blocks.blocksvg', verbose_name='"Как мы работаем?"'),
        ),
    ]
