# Generated by Django 4.1.7 on 2023-09-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staircases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staircase',
            options={'verbose_name': 'лестницу', 'verbose_name_plural': 'лестницы'},
        ),
        migrations.RemoveField(
            model_name='staircase',
            name='menu_name',
        ),
        migrations.RemoveField(
            model_name='staircase',
            name='menu_order',
        ),
    ]
