# Generated by Django 4.1.7 on 2023-06-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staircases', '0002_staircase_hwaw'),
    ]

    operations = [
        migrations.AddField(
            model_name='staircase',
            name='portfolio_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
    ]
