# Generated by Django 4.1.7 on 2023-06-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staircases', '0002_remove_staircase_portfolio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='staircase',
            name='is_calculator',
            field=models.BooleanField(default=1, verbose_name='показывать'),
        ),
    ]
