# Generated by Django 4.1.7 on 2023-06-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staircases', '0003_remove_staircase_meta_keywords_alter_staircase_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staircase',
            old_name='prices',
            new_name='block_price',
        ),
    ]
