# Generated by Django 4.1.7 on 2023-06-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staircases', '0004_staircase_block_railings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaircaseTypicalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('frame_material', models.CharField(max_length=250, verbose_name='материал каркаса')),
                ('frame_width', models.PositiveSmallIntegerField(null=True, verbose_name='ширина каркаса, мм')),
                ('frame_thickness', models.PositiveSmallIntegerField(null=True, verbose_name='толщина каркаса, мм')),
                ('frame_material2', models.CharField(max_length=250, verbose_name='материал каркаса')),
                ('frame_width2', models.PositiveSmallIntegerField(null=True, verbose_name='ширина каркаса, мм')),
                ('frame_thickness2', models.PositiveSmallIntegerField(null=True, verbose_name='толщина каркаса, мм')),
                ('frame_kosour_count', models.PositiveSmallIntegerField(null=True, verbose_name='количество косоуров')),
                ('coloring', models.CharField(max_length=250, verbose_name='окраска')),
                ('steps_material', models.CharField(max_length=250, verbose_name='материал ступеней')),
                ('steps_height', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='высота ступеней, м')),
            ],
            options={
                'verbose_name': 'типовой проект',
                'verbose_name_plural': 'типовой проект',
            },
        ),
        migrations.AddField(
            model_name='staircase',
            name='typical_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staircases.staircasetypicalproject', verbose_name='типичный проект'),
        ),
    ]
