# Generated by Django 4.1.7 on 2023-06-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staircases', '0005_staircasetypicalproject_staircase_typical_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staircasetypicalproject',
            name='frame_material',
        ),
        migrations.RemoveField(
            model_name='staircasetypicalproject',
            name='frame_material2',
        ),
        migrations.RemoveField(
            model_name='staircasetypicalproject',
            name='frame_thickness',
        ),
        migrations.RemoveField(
            model_name='staircasetypicalproject',
            name='frame_thickness2',
        ),
        migrations.RemoveField(
            model_name='staircasetypicalproject',
            name='frame_width',
        ),
        migrations.RemoveField(
            model_name='staircasetypicalproject',
            name='frame_width2',
        ),
        migrations.AddField(
            model_name='staircasetypicalproject',
            name='frame_broken_material',
            field=models.CharField(default='', max_length=250, verbose_name='материал "ломаного" каркаса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staircasetypicalproject',
            name='frame_broken_thickness',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='толщина "ломаного" каркаса, мм'),
        ),
        migrations.AddField(
            model_name='staircasetypicalproject',
            name='frame_broken_width',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='ширина "ломаного" каркаса, мм'),
        ),
        migrations.AddField(
            model_name='staircasetypicalproject',
            name='frame_straight_material',
            field=models.CharField(default='', max_length=250, verbose_name='материал "прямого" каркаса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staircasetypicalproject',
            name='frame_straight_thickness',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='толщина "прямого" каркаса, мм'),
        ),
        migrations.AddField(
            model_name='staircasetypicalproject',
            name='frame_straight_width',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='ширина "прямого" каркаса, мм'),
        ),
    ]
