# Generated by Django 4.1.7 on 2023-06-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staircases', '0006_remove_staircasetypicalproject_frame_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staircasetypicalproject',
            name='frame_broken_material',
            field=models.CharField(blank=True, max_length=250, verbose_name='материал "ломаного" каркаса'),
        ),
        migrations.AlterField(
            model_name='staircasetypicalproject',
            name='frame_broken_thickness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='толщина "ломаного" каркаса, мм'),
        ),
        migrations.AlterField(
            model_name='staircasetypicalproject',
            name='frame_broken_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ширина "ломаного" каркаса, мм'),
        ),
        migrations.AlterField(
            model_name='staircasetypicalproject',
            name='frame_straight_material',
            field=models.CharField(blank=True, max_length=250, verbose_name='материал "прямого" каркаса'),
        ),
        migrations.AlterField(
            model_name='staircasetypicalproject',
            name='frame_straight_thickness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='толщина "прямого" каркаса, мм'),
        ),
        migrations.AlterField(
            model_name='staircasetypicalproject',
            name='frame_straight_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ширина "прямого" каркаса, мм'),
        ),
    ]
