# Generated by Django 4.1.7 on 2023-06-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staircases', '0009_alter_staircase_typical_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staircasetypicalproject',
            name='frame_kosour_count',
        ),
    ]
