# Generated by Django 4.1.7 on 2023-06-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_alter_steps_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='meta_keywords',
        ),
        migrations.AlterField(
            model_name='steps',
            name='name',
            field=models.CharField(max_length=80, verbose_name='h1-название'),
        ),
    ]
