# Generated by Django 4.1.7 on 2023-06-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridge',
            name='meta_keywords',
        ),
        migrations.AlterField(
            model_name='bridge',
            name='name',
            field=models.CharField(max_length=80, verbose_name='h1-название'),
        ),
    ]
