# Generated by Django 4.1.7 on 2023-08-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='purpose',
            field=models.CharField(choices=[('', 'None'), ('M', 'Модерн'), ('C', 'Классика'), ('A', 'Ар-деко'), ('S', 'Современное')], default='', max_length=2, verbose_name=''),
        ),
    ]
