# Generated by Django 4.1.7 on 2023-08-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='purpose',
            field=models.CharField(choices=[('', 'None'), ('M', 'Модерн'), ('C', 'Классика'), ('A', 'Ар-деко'), ('S', 'Современное')], default='', max_length=2, verbose_name='назначение'),
        ),
    ]
