# Generated by Django 4.1.7 on 2023-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', 'None'), ('M', 'Модерн'), ('C', 'Классика'), ('A', 'Ар-деко'), ('S', 'Современное')], default='', max_length=2, verbose_name='назначение'),
        ),
    ]
