# Generated by Django 4.1.7 on 2023-08-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_image_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', 'None'), ('M', 'Ограждение «Модерн»'), ('C', 'Ограждение «Классика»'), ('A', 'Ограждение «Ар-деко»'), ('S', 'Ограждение «Современное»')], default='', max_length=2, verbose_name='назначение'),
        ),
    ]
