# Generated by Django 4.1.7 on 2023-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeff_h', models.PositiveSmallIntegerField(default=0, verbose_name='коэффициент высоты')),
                ('delivery', models.PositiveSmallIntegerField(default=0, verbose_name='доставка')),
                ('installation', models.PositiveSmallIntegerField(default=0, verbose_name='установка')),
            ],
            options={
                'verbose_name': 'калькулятор',
                'verbose_name_plural': 'калькулятор',
            },
        ),
        migrations.CreateModel(
            name='RailingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='название')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='цена')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('order_number', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
            ],
            options={
                'verbose_name': 'тип ограждения',
                'verbose_name_plural': 'тип ограждения',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='StepsMaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='название')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='цена')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('order_number', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
            ],
            options={
                'verbose_name': 'тип материала ступеней',
                'verbose_name_plural': 'тип материала ступеней',
                'ordering': ['order_number'],
            },
        ),
    ]
