# Generated by Django 4.1.7 on 2023-06-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='delivery',
            field=models.PositiveIntegerField(default=0, verbose_name='доставка'),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='installation',
            field=models.PositiveIntegerField(default=0, verbose_name='установка'),
        ),
    ]
