# Generated by Django 4.1.7 on 2023-06-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_calculator_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='название')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='цена')),
                ('order_number', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
            ],
            options={
                'verbose_name': 'тип ограждения',
                'verbose_name_plural': 'тип ограждений',
                'ordering': ['order_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='railingtype',
            options={'ordering': ['order_number'], 'verbose_name': 'тип ограждения', 'verbose_name_plural': 'тип ограждений'},
        ),
    ]
