# Generated by Django 4.1.7 on 2023-06-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_service_alter_railingtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order_number'], 'verbose_name': 'услуга', 'verbose_name_plural': 'услуги'},
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='installation',
        ),
    ]
