# Generated by Django 4.1.7 on 2023-06-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_service_options_remove_calculator_delivery_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calculator',
            new_name='Coeff',
        ),
        migrations.AlterModelOptions(
            name='coeff',
            options={'verbose_name': 'коэффициент', 'verbose_name_plural': 'коэффициенты'},
        ),
        migrations.RenameField(
            model_name='coeff',
            old_name='coeff_h',
            new_name='h',
        ),
    ]
