# Generated by Django 4.1.7 on 2023-06-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_rename_calculator_coeff_alter_coeff_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoeffStaircaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='название')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='цена')),
                ('order_number', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
            ],
            options={
                'verbose_name': 'Коэффициент для типа лестницы',
                'verbose_name_plural': 'Коэффициенты для типов лестницы',
                'ordering': ['order_number'],
            },
        ),
    ]
