# Generated by Django 4.1.7 on 2023-06-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name': 'главная страница', 'verbose_name_plural': 'главные страницы'},
        ),
    ]
