# Generated by Django 4.1.7 on 2023-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_indexpage_hwaw'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='portfolio_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
    ]
