# Generated by Django 4.1.7 on 2023-06-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_index_portfolio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='is_calculator',
            field=models.BooleanField(default=1, verbose_name='показывать'),
        ),
    ]
