# Generated by Django 4.1.7 on 2023-06-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        ('index', '0002_alter_indexpage_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexPage',
            new_name='Index',
        ),
    ]
