# Generated by Django 4.1.7 on 2023-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        ('index', '0007_alter_index_block_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='block_price',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='+', to='blocks.blockprice', verbose_name='"Цены"'),
        ),
    ]
