# Generated by Django 4.1.7 on 2023-09-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Railing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=80, verbose_name='title')),
                ('meta_description', models.CharField(max_length=160, verbose_name='meta description')),
                ('name', models.CharField(max_length=80, verbose_name='h1-название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='url-адрес страницы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('description_title', models.CharField(blank=True, max_length=200, verbose_name='заголовок')),
                ('description_text', models.TextField(blank=True, verbose_name='текст')),
                ('portfolio_title_m', models.CharField(blank=True, max_length=200, verbose_name='заголовок')),
                ('portfolio_text_m', models.TextField(blank=True, verbose_name='текст')),
                ('portfolio_title_c', models.CharField(blank=True, max_length=200, verbose_name='заголовок')),
                ('portfolio_text_c', models.TextField(blank=True, verbose_name='текст')),
                ('portfolio_title_a', models.CharField(blank=True, max_length=200, verbose_name='заголовок')),
                ('portfolio_text_a', models.TextField(blank=True, verbose_name='текст')),
                ('portfolio_title_s', models.CharField(blank=True, max_length=200, verbose_name='заголовок')),
                ('portfolio_text_s', models.TextField(blank=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'ограждение',
                'verbose_name_plural': 'ограждения',
            },
        ),
    ]
