# Generated by Django 4.1.7 on 2023-06-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railing',
            name='description_text',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='railing',
            name='description_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='заголовок'),
        ),
    ]
