# Generated by Django 4.1.7 on 2023-09-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='railing',
            options={'verbose_name': 'ограждение', 'verbose_name_plural': 'ограждения'},
        ),
        migrations.RemoveField(
            model_name='railing',
            name='menu_name',
        ),
        migrations.RemoveField(
            model_name='railing',
            name='menu_order',
        ),
    ]
