# Generated by Django 4.1.7 on 2023-06-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railings', '0002_remove_railing_portfolio_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='railing',
            options={'ordering': ('menu_order',), 'verbose_name': 'ограждение', 'verbose_name_plural': 'ограждения'},
        ),
    ]
