# Generated by Django 4.1.7 on 2023-08-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railings', '0002_railing_portfolio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='railing',
            name='a_text',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='railing',
            name='a_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='railing',
            name='c_text',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='railing',
            name='c_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='railing',
            name='m_text',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='railing',
            name='m_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='railing',
            name='s_text',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='railing',
            name='s_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='заголовок'),
        ),
    ]
