# Generated by Django 4.1.7 on 2023-08-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railings', '0003_railing_a_text_railing_a_title_railing_c_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='railing',
            old_name='a_text',
            new_name='portfolio_text_a',
        ),
        migrations.RenameField(
            model_name='railing',
            old_name='c_text',
            new_name='portfolio_text_c',
        ),
        migrations.RenameField(
            model_name='railing',
            old_name='m_text',
            new_name='portfolio_text_m',
        ),
        migrations.RenameField(
            model_name='railing',
            old_name='s_text',
            new_name='portfolio_text_s',
        ),
        migrations.RenameField(
            model_name='railing',
            old_name='a_title',
            new_name='portfolio_title_a',
        ),
        migrations.RenameField(
            model_name='railing',
            old_name='c_title',
            new_name='portfolio_title_c',
        ),
        migrations.RenameField(
            model_name='railing',
            old_name='m_title',
            new_name='portfolio_title_m',
        ),
        migrations.RenameField(
            model_name='railing',
            old_name='s_title',
            new_name='portfolio_title_s',
        ),
    ]
