# Generated by Django 4.1.7 on 2023-08-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railings', '0004_rename_a_text_railing_portfolio_text_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railing',
            name='portfolio_title',
        ),
    ]
