# Generated by Django 4.1.7 on 2023-09-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_slug_alter_menu_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'меню', 'verbose_name_plural': 'меню'},
        ),
        migrations.AddField(
            model_name='menu',
            name='app_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='название приложения'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=30, verbose_name='название'),
        ),
    ]
