# Generated by Django 4.1.7 on 2023-09-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_options_menu_app_name_alter_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='app_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='path_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='menu',
            name='path_namespace',
            field=models.CharField(blank=True, max_length=30, verbose_name='namespace'),
        ),
    ]
