# Generated by Django 4.1.7 on 2023-09-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_dropdown',
            field=models.BooleanField(default=0, verbose_name='выпадающее меню'),
        ),
    ]
