# Generated by Django 4.1.7 on 2023-09-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menu_is_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_dropdown',
            field=models.BooleanField(default=0, verbose_name='выпадающее меню?'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_visible',
            field=models.BooleanField(default=1, verbose_name='показывать?'),
        ),
    ]
