# Generated by Django 4.1.7 on 2023-09-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menu_is_dropdown_alter_menu_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_dropdown',
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='url-адрес страницы'),
        ),
    ]
